apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: friendly-e-shop
  namespace: apps
  annotations: {cert-manager.io/cluster-issuer: letsencrypt-prod}
spec:
  ingressClassName: traefik
  tls:
    - hosts: [market.REPLACE_BASE_DOMAIN, panel.REPLACE_BASE_DOMAIN, api.REPLACE_BASE_DOMAIN]
      secretName: friendly-e-shop-tls
  rules:
    - host: market.REPLACE_BASE_DOMAIN
      http: {paths: [{path: /, pathType: Prefix, backend: {service: {name: client-web, port: {number: 8080}}}}]}
    - host: panel.REPLACE_BASE_DOMAIN
      http: {paths: [{path: /, pathType: Prefix, backend: {service: {name: panel-web, port: {number: 8080}}}}]}
    - host: api.REPLACE_BASE_DOMAIN
      http:
        paths:
          - {path: /accounts, pathType: Prefix, backend: {service: {name: account-api, port: {number: 8080}}}}
          - {path: /catalog, pathType: Prefix, backend: {service: {name: catalog-api, port: {number: 8080}}}}
          - {path: /orders, pathType: Prefix, backend: {service: {name: order-api, port: {number: 8080}}}}
          - {path: /payments, pathType: Prefix, backend: {service: {name: payment-api, port: {number: 8080}}}}
          - {path: /panel, pathType: Prefix, backend: {service: {name: panel-api, port: {number: 8000}}}}
