apiVersion: v1
kind: Secret
metadata: {name: app-secrets, namespace: apps, annotations: {friendly-e-shop.io/replace-before-deploy: "true"}}
type: Opaque
stringData:
  account-db-password: REPLACE_ME
  catalog-db-password: REPLACE_ME
  orders-db-password: REPLACE_ME
  payments-db-password: REPLACE_ME
  panel-db-password: REPLACE_ME
  rabbitmq-password: REPLACE_ME
  django-secret-key: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata: {name: platform-secrets, namespace: platform, annotations: {friendly-e-shop.io/replace-before-deploy: "true"}}
type: Opaque
stringData:
  postgres-admin-password: REPLACE_ME
  account-db-password: REPLACE_ME
  catalog-db-password: REPLACE_ME
  orders-db-password: REPLACE_ME
  payments-db-password: REPLACE_ME
  panel-db-password: REPLACE_ME
  rabbitmq-password: REPLACE_ME
  minio-root-user: REPLACE_ME
  minio-root-password: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata: {name: grafana-cloud-credentials, namespace: observability, annotations: {friendly-e-shop.io/replace-before-deploy: "true"}}
type: Opaque
stringData:
  otlp-endpoint: https://otlp-gateway-REPLACE_ME.grafana.net/otlp
  authorization: Basic_REPLACE_ME
