apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-api
  namespace: apps
spec:
  template:
    spec:
      containers:
        - name: account-api
          env:
            - name: SESSION_COOKIE_DOMAIN
              value: .friendly-e-shop.duckdns.org
            - name: SESSION_COOKIE_SECURE
              value: "true"
            - name: BROWSER_ORIGINS
              value: https://market.friendly-e-shop.duckdns.org,https://panel.friendly-e-shop.duckdns.org
            - name: PUBLIC_API_BASE_URL
              value: https://api.friendly-e-shop.duckdns.org
