apiVersion: v1
kind: ConfigMap
metadata: {name: panel-api-config, namespace: apps}
data:
  PANEL_PUBLIC_ORIGIN: https://panel.friendly-e-shop.duckdns.org
  ACCOUNTS_PUBLIC_BASE_URL: https://api.friendly-e-shop.duckdns.org
