apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: apps
  labels: {app.kubernetes.io/name: catalog-api}
spec:
  selector: {app.kubernetes.io/name: catalog-api}
  ports: [{name: http, port: 8080, targetPort: http}]
