apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - account-api
  - catalog-api
  - order-api
  - payment-api
  - client-web
  - panel-api
  - panel-web
  - platform
  - observability
labels:
  - pairs: {app.kubernetes.io/managed-by: kustomize}
    includeSelectors: false
