apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: apps
spec:
  template:
    spec:
      containers:
        - name: order-api
          env:
            - name: JAVA_DEBUG_OPTS
              value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=127.0.0.1:5007