apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - resources/secrets.yaml
  - resources/ingress.yaml
  - resources/network-policies.yaml
  - resources/observability-local.yaml
configMapGenerator:
  - name: java-dev-reload
    namespace: apps
    files:
      - reload.sh=../../../scripts/java-dev-reload.sh
    options:
      disableNameSuffixHash: true
patches:
  - path: patches/otel-config-patch.yaml
  - path: patches/account-api-env-patch.yaml
  - path: patches/panel-api-env-patch.yaml
  - path: patches/panel-api-image-pull.yaml
  - path: patches/apps-namespace.yaml
  - path: patches/live/panel-web.yaml
  - path: patches/live/client-web.yaml
  - path: patches/live/panel-api.yaml
  - path: patches/live/account-api.yaml
  - path: patches/live/catalog-api.yaml
  - path: patches/live/order-api.yaml
  - path: patches/live/payment-api.yaml
  - target: {group: apps, version: v1, kind: Deployment, namespace: apps}
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
