apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - secrets.yaml
  - ingress.yaml
  - network-policies.yaml
  - observability-local.yaml
patches:
  - path: otel-config-patch.yaml
  - path: account-api-env-patch.yaml
  - path: panel-api-env-patch.yaml
  - target: {group: apps, version: v1, kind: Deployment, namespace: apps}
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
