apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - resources/secrets.yaml
  - resources/ingress.yaml
  - resources/network-policies.yaml
  - resources/observability-local.yaml
configMapGenerator:
  - name: java-dev-reload
    namespace: apps
    files:
      - reload.sh=../../../scripts/runtime/java-dev-reload.sh
    options:
      disableNameSuffixHash: true
patches:
  - path: patches/shared/otel-config-patch.yaml
  - path: patches/shared/apps-namespace.yaml
  - path: patches/account-api/env-patch.yaml
  - path: patches/account-api/debug.yaml
  - path: patches/account-api/live.yaml
  - path: patches/catalog-api/env-patch.yaml
  - path: patches/catalog-api/debug.yaml
  - path: patches/catalog-api/live.yaml
  - path: patches/order-api/debug.yaml
  - path: patches/order-api/live.yaml
  - path: patches/payment-api/debug.yaml
  - path: patches/payment-api/live.yaml
  - path: patches/panel-api/env-patch.yaml
  - path: patches/panel-api/image-pull.yaml
  - path: patches/panel-api/live.yaml
  - path: patches/client-web/live.yaml
  - path: patches/panel-web/live.yaml
  - target: {group: apps, version: v1, kind: Deployment, namespace: apps}
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
