apiVersion: v1
kind: Secret
metadata: {name: app-secrets, namespace: apps}
type: Opaque
stringData:
  catalog-db-password: catalog-local
  orders-db-password: orders-local
  payments-db-password: payments-local
  panel-db-password: panel-local
  rabbitmq-password: rabbit-local
  django-secret-key: local-only-not-for-production
---
apiVersion: v1
kind: Secret
metadata: {name: platform-secrets, namespace: platform}
type: Opaque
stringData:
  postgres-admin-password: postgres-local
  catalog-db-password: catalog-local
  orders-db-password: orders-local
  payments-db-password: payments-local
  panel-db-password: panel-local
  rabbitmq-password: rabbit-local
  minio-root-user: minio
  minio-root-password: minio-local-password
---
apiVersion: v1
kind: Secret
metadata: {name: observability-secrets, namespace: observability}
type: Opaque
stringData: {grafana-admin-password: grafana-local}
